- name: Create downloads directory
  file:
    path: '{{ qutebrowser.download_directory }}'
    state: directory

- name: Create qutebrowser configuration directory
  file:
    path: '{{ config_dir }}/qutebrowser/'
    state: directory

- name: Create qutebrowser configuration file from template
  template:
    src: config.py
    dest: '{{ config_dir }}/qutebrowser/config.py'
