- name: Create Neovim configuration directory
  file:
    path: '{{ config_dir }}/nvim/'
    state: directory

- name: Copy Neovim configuration file
  copy:
    src: init.vim
    dest: '{{ config_dir }}/nvim/'
